### ISSUE TITLE
file can't upload

### ISSUE THREAD

**Issue by wlc002** [3Alan/chat-markdown#2]
![微信截图_20230410144828](https://user-images.githubusercontent.com/16040091/230844111-f6b0eac0-39c4-497e-a9aa-bf47feb2b4bb.png)

**Comment by 3Alan** [comment]
因为要部署Demo，默认生产环境关闭了上传功能（Railway免费的额度不够没办法让大家上传自己文件），你需要在本地运行（页面上黄色区域已经说明过了）。

**Comment by wlc002** [comment]
明白，我是在vercel部署的，如何开启upload功能？

**Comment by 3Alan** [comment]
vercel只能部署前端，python代码你需要另外部署到你的服务器，我等下会将是否开启上传功能单独使用一个环境变量来判断（目前是判断是否是生产环境）

**Comment by wlc002** [comment]
👍👍期待

**Comment by 3Alan** [comment]
看着是VITE_SERVICES_URL没有值，要么拼写错误要么添加后没重新deploy
